[package]
name = "rsautogui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.0.14"
scrap = "0.5.0"
image = "0.24.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
